/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./../components/baseComponents/BaseAlert/index.vue')['default']
    BaseDialog: typeof import('./../components/baseComponents/BaseDialog/index.vue')['default']
    BaseToast: typeof import('./../components/baseComponents/BaseToast/index.vue')['default']
    Help: typeof import('./../components/baseComponents/Help/index.vue')['default']
    MultipleMatches: typeof import('./../components/MultipleMatches/index.vue')['default']
    Overlay: typeof import('./../components/baseComponents/Overlay/index.vue')['default']
    PageLoading: typeof import('./../components/baseComponents/PageLoading/index.vue')['default']
    ProductListItem: typeof import('./../components/ProductListItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search/index.vue')['default']
    Separate: typeof import('./../components/baseComponents/Separate/index.vue')['default']
    SvgIcon: typeof import('./../components/baseComponents/SvgIcon/index.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
  }
}
